name: Pre-Release

on:
  push:
    branches: ["main-dev"]
  pull_request:
    branches: ["main-dev"]

permissions:
  contents: write

jobs:
  semver:
    runs-on: ubuntu-latest
    name: Update Version
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run TinySemVer
        uses: ./ # This uses the action defined in the current repository
        with:
          verbose: "true"
          changelog-file: "CHANGELOG.md"
          version-file: "VERSION"
          update-version-in: 'pyproject.toml:version = "(.*)"'
          dry-run: "true"
